### ISSUE TITLE
Submitting a package doesn't work as advertised

### ISSUE THREAD

**Issue by pepa65** [bpkg/bpkg.github.io#29]
Hi there!
I'm trying to follow the instructions to submit a package on http://www.bpkg.io/submit/
As the instructions said, I cloned, created a new branch, written the post according to the guidelines, added and committed it, but here I am stuck.

Usually I would have forked, then eventually pushed the changes, and then submitted a pull request.
The instructions say to "make a pull request with your changes to our repository. The GitHub web interface has nice green buttons for that."

So I went to look at https://github.com/bpkg/bpkg.github.io but the only green button says "Clone or download"...

How do I proceed?

**Comment by jwerle** [comment]
@pepa65 you need to submit a PR back to this repository

**Comment by pepa65** [comment]
Right. Could you please tell me in more detail how I could do that?

**Comment by jwerle** [comment]
@pepa65 
1. Fork this repository
2. Clone it down locally
3. [Add a new post with the title of your package](https://github.com/bpkg/bpkg.github.io#how-to-edit)
4. Push it up to the fork
5. Issue a PR to this upstream from your fork

**Comment by pepa65** [comment]
In that case the instructions should be upgraded to fork the repo first! I am familiar with the procedure you describe. Thanks for persisting!

**Comment by pepa65** [comment]
Maybe I shouldn't have closed it, as the instructions on submitting are still broken...
