### ISSUE TITLE
Organization links still point to bpkg.io

### ISSUE THREAD

**Issue by unascribed** [bpkg/bpkg.github.io#42]
The links on https://github.com/bpkg still point to the (hijacked?) bpkg.io.

**Comment by Potherca** [comment]
Thanks for reporting this!

I've updated th URL to [bpkg.sh](http://bpkg.sh/)

@jwerle What should the email be changed to? (it currently points to  `info@bpkg.io`)

![bpkg](https://user-images.githubusercontent.com/195757/37401640-090d997e-2789-11e8-9e42-60ecb2c18f7a.png)

**Comment by jwerle** [comment]
info@bpkg.sh should work!

**Comment by Potherca** [comment]
Fixed.
