### ISSUE TITLE
bpkg.io hosts alternative version of site

### ISSUE THREAD

**Issue by stevvooe** [bpkg/bpkg.github.io#43]
If we go to bpkg.io, we seen some information about astrology:

![screenshot from 2018-05-31 10 28 23](https://user-images.githubusercontent.com/120601/40797610-a752fcde-64bd-11e8-9c36-02de509ad385.png)

It looks like the official site is bpkg.sh but bpkg.io comes up first in results. You may want to look into this, as it can cause confusion with users or possibly lead to the malicious installation of software.

**Comment by Potherca** [comment]
Do you have any suggestions as to what should be done?

**Comment by Potherca** [comment]
Looks like whomever is behind it is not paying too much attention:

![image](https://user-images.githubusercontent.com/195757/63385076-88464100-c3a0-11e9-85af-8e243b2ef615.png)

**Comment by Potherca** [comment]
Closing this as bpkg.io is currently obviously a parked domain.
