### ISSUE TITLE
Background does not cover full height on long pages

### ISSUE THREAD

**Issue by Potherca** [bpkg/bpkg.github.io#70]
The latest changes for full-height on smaller content has caused full-height to break on longer content.

This is caused because the height is set to 100% but the page is longer than 100%.

![image](https://user-images.githubusercontent.com/195757/229453616-191595c9-e64c-492a-8461-85f224f20521.png)

Setting the `min-height` to 100% would fix this for long pages but break for short pages

![image](https://user-images.githubusercontent.com/195757/229454241-4c4d5b48-2d27-4ffb-bcea-1ca80f838d9b.png)

The solution would be to set both height and min-height on the `body` but only min-height on `#page`:

```css
body {
    min-height: 100%;
    height: 100%;
}

#page {
    min-height: 100%;
}
```

I don't have time to fix the code right now, if nobody else picks this up, I'll come back to it later.

**Comment by samlikins** [comment]
@Potherca, you're absolutely correct.  I didn't notice that issue, the problem didn't seem to show on my local preview for longer pages.  Updates have been made.

**Comment by samlikins** [comment]
PR #71, compared, merged, and closed.

**Comment by Potherca** [comment]
@samlikins No worries! 👍
